almacenes/pedidos/urls.py
from django.urls import path
from .views import index, lista_pedido_por_id,realizar_entrega,imprecion_solicitud,autorizar_pedidos_almacen,listando_pedido_almacen,generate_pdf,buscador,mostrar_informacion_pedidio_aprobaciones, realizar_pedido, listar_pedidos, mis_pedidos,todos_mis_pedidos, listar_pedidos_unidad, autorizar_pedidos, rechazar_pedido_unidad, eliminar_mi_pedido

urlpatterns = [
   path('index',index , name='index' ),
   path('buscar',buscador , name='buscar' ),
   path('realizar_pedido/<int:id_material>',realizar_pedido , name='realizar_pedido' ),
   path('listando_pedidos',listar_pedidos , name='listando_pedidos' ),
   path('informacion_pedido/<int:id_usuario>',listando_pedido_almacen , name='informacion_pedido' ),
   path('mis_pedidos',mis_pedidos , name='mis_pedidos' ),
   path('todos_mis_pedidos',todos_mis_pedidos, name='todos_mis_pedidos' ),
   path('listar_pedidos_unidad/<int:id_usuario>',listar_pedidos_unidad, name='listar_pedidos_unidad' ),
   path('autorizar_pedido/<int:id_pedido>',autorizar_pedidos, name='autorizar_pedido' ),
   path('autorizar_pedido_almacen/<int:id_pedido>/<int:id_usuario>',autorizar_pedidos_almacen, name='autorizar_pedido_almacen' ),
   path('rechazar_pedido_unidad/<int:id_pedido>',rechazar_pedido_unidad, name='rechazar_pedido_unidad' ),
   path('eliminar_mi_pedido/<int:id_pedido>',eliminar_mi_pedido, name='eliminar_mi_pedido'),
   path('informacion/pedido/<int:id_pedido>' , mostrar_informacion_pedidio_aprobaciones , name="info_aprobaciones" ),
   path('imprimir/<int:id_pedido>',imprecion_solicitud, name='imprimir' ),
   path('generar/pdf/<int:id_pedido>',generate_pdf, name='pdf' ),
    path('informacion_pedido/lista_pedido_por_id/<int:id_pedido>',lista_pedido_por_id, name='lista_pedido_por_id' ),
      path('informacion_pedido/realizar_entrega',realizar_entrega, name='realizar_entrega' )
   
]

almacenes/urls.py
from django.urls import path, include 
urlpatterns = [
    path('proveedor/' ,include('almacenes.proveedor.urls')),#urls proveedor
    path('material/' ,include('almacenes.materiales.urls')),#urls materiales
    path('', include('almacenes.pedidos.urls')),
    path('', include('almacenes.usuarios.urls')),
    path('',include('almacenes.administracion.urls') )
    
    
]

almacenes/usuarios/urls.py
from django.urls import path, include 
from .views  import login_sistema, crear_oficinas,Crear_unidad_secretaria,logout_view,crear_unidad_listar,oficinas_listar, creando_usuario, listando_usuarios, crear_secretaria_listar,soft_delete, activar_cuenta, desactivar_cuenta, actulizar_cuenta_usuario
urlpatterns = [

    path("", login_sistema, name="login"),
    path("creando_usuarios", creando_usuario, name="creando_usuarios"),
    path('listando_usuarios',listando_usuarios,name='listando_usuarios' ),
    path('crear_secretaria_listar',crear_secretaria_listar,name='crear_secretaria_listar' ),
    path('eliminar/<int:id>', soft_delete, name='eliminar_cuenta') ,
    path('activar_cuenta/<int:id>', activar_cuenta, name='activar_cuenta') ,
    path('desactivar_cuenta/<int:id>', desactivar_cuenta, name='desactivar_cuenta') ,
    path('actulizar_cuenta_usuario/<int:id_usuario>/<int:id_persona>', actulizar_cuenta_usuario, name='actulizar_cuenta_usuario') ,
    path("logout", logout_view, name='logout'),
    path("unidad",crear_unidad_listar , name='unidad' ),
    path('oficinas/<int:id_unidad>',oficinas_listar, name='oficinas'),
    path('crear_oficinas',crear_oficinas, name='crear_oficinas'),
    path('Crear_unidad_secretaria', Crear_unidad_secretaria, name='Crear_unidad_secretaria')
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('almacenes.urls') )
]

almacenes/models.py
from django.db import models


    

almacenes/pedido/models.py
from django.db import models
from  ..usuarios.models import Usuario
from ..productos.models import Productos
class Pedido(models.Model):
    descripcion =models.TextField()
    pedido_usario=models.IntegerField()
    entrega_almacen=models.IntegerField()
    total_pedido=models.IntegerField()
    precio_paquete= models.DecimalField(max_digits=10, decimal_places=2)
    cantidad=models.IntegerField()
    total=models.DecimalField(max_digits=10, decimal_places=2)
    estado_pedido = models.BooleanField(default=False)
    usuario=models.ForeignKey(Usuario , models.CASCADE)
    productos= models.ManyToManyField(Productos, through='DetallePedido')   

class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)

almacenes/usuarios/models.py
from django.contrib.auth.models import AbstractBaseUser , UserManager, PermissionsMixin
from django.dispatch import receiver
from django.db.models.signals import post_migrate
from django.db import models
from ..persona.models import Persona






    




class Secretaria(models.Model):
    secretaria = models.CharField(max_length=100, blank=False , null=False, unique=True)
    def __str__(self) -> str:
        return f"{self.secretaria}"
    

class Unidad(models.Model):
    nombre =models.CharField(max_length=100,blank=False, null=False, unique=True )
    secretaria=models.ForeignKey(Secretaria, on_delete=models.RESTRICT, blank= True, null=True)
    def __str__(self) -> str:
        return f"{self.nombre}"
    
class Oficinas(models.Model):
    nombre =models.CharField(max_length=100,blank=False, null=False, unique=True)
    unidad=models.ForeignKey(Unidad, on_delete=models.RESTRICT, blank= True, null=True)
    def __str__(self) -> str:
        return f"{self.nombre}"
@receiver(post_migrate)
def crear_entidades_por_defecto(sender, **kwargs):
    if sender.name == 'almacenes.usuarios':
        secretaria, created = Secretaria.objects.get_or_create(secretaria='Secretaria departamental administrativa financiera')
        unidad, created = Unidad.objects.get_or_create(nombre='Financiera', secretaria=secretaria)
        Oficinas.objects.get_or_create(nombre='Ninguna', unidad=unidad)
        Oficinas.objects.get_or_create(nombre='Almacenes', unidad=unidad)
      

    
class Usuario(AbstractBaseUser, PermissionsMixin):
    ENCARGADO=[
        (True,'Encargado'),
        (False,'Personal')
    ]
    ROLES_CHOICES=[
        ('Administrador','Administrador'),
        ('Super_administrador','Super administrador'),
        ('Axuliar','Axuliar'),
        ('Personal','Personal')
    ]
    username= models.CharField(max_length=150, unique=True, blank=False, null=False, verbose_name='Usuario')
    password = models.CharField(max_length=128, blank=False, null=False, verbose_name='Contraseña')
    email=models.EmailField(max_length=255, blank=True, null=True)
    item = models.CharField(max_length=100, blank=True, null=True)
    is_staff= models.CharField(default=True)#desactivar usuario
    encargado=models.BooleanField(blank=False, null=False, choices=ENCARGADO, default=False, verbose_name='Jefe  de la secretaria' ) 
    crear = models.BooleanField(default=False,verbose_name='Crear material')
    editar= models.BooleanField(default=False,verbose_name='editar material')
    eliminar=models.BooleanField(default=False,verbose_name='Eliminar material')
    rol=models.CharField(max_length=250, choices=ROLES_CHOICES, default='Personal')
    unidad= models.ForeignKey(Unidad, on_delete=models.RESTRICT,blank=True, null=True)
    oficina= models.ForeignKey(Oficinas, on_delete=models.RESTRICT,blank=True, null=True)
    persona = models.ForeignKey(Persona, on_delete=models.RESTRICT)

    es_habilitado=models.BooleanField(default=True)
    es_activo=models.BooleanField(default=True)

    
    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['rol']
    def __str__(self) -> str:
        return f" Activo:{self.es_activo}"

almacenes/materiales/forms.py
from typing import Any
from django import forms
from .models import Categoria, Materiales

class Formulario_materiales(forms.ModelForm):
    class Meta:
        model=Materiales
        fields = ['nombre', 'codigo','codigo_paquete' , 'marca', 'cantidad_paquete', 'cantidad_paquete_unidad', 'precio_paquete','precio_unidad',  'tamaño', 'color', 'unidad_medida', 'material', 'categoria']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control',}),
            'codigo': forms.TextInput(attrs={'class': 'form-control'}),
            'marca': forms.TextInput(attrs={'class': 'form-control'}),
            'cantidad_paquete': forms.TextInput(attrs={'class': 'form-control'}),
            'tamaño': forms.TextInput(attrs={'class': 'form-control'}),
            'color': forms.TextInput(attrs={'class': 'form-control'}),
            'unidad_medida': forms.TextInput(attrs={'class': 'form-control'}),
            'material': forms.TextInput(attrs={'class': 'form-control'}),
            'codigo_paquete': forms.TextInput(attrs={'class': 'form-control'}),
            'cantidad_paquete_unidad': forms.TextInput(attrs={'class': 'form-control'}),
            'precio_paquete': forms.TextInput(attrs={'class': 'form-control'}),
            'precio_unidad': forms.TextInput(attrs={'class': 'form-control'})
        }
     
    def __init__(self, *args, **kwargs):#mostrando en un select todas las categorias disponibles
        super(Formulario_materiales,self).__init__(*args, **kwargs)
        categorias_disponibles = [(categoria.id, categoria.nombre) for categoria in Categoria.objects.all()]#consultado a la base de datos     
        self.fields['categoria'].widget = forms.Select(choices=categorias_disponibles, attrs={'class': 'form-select'})
        self.fields['categoria'].widget.attrs.update({'class': 'form-select'})

        instance = kwargs.get('instance')
        if instance:
            # Establecer campos de solo lectura
            self.fields['codigo'].widget.attrs['readonly'] = True
            self.fields['codigo_paquete'].widget.attrs['readonly'] = True
class Formulario_categoria(forms.ModelForm):
    class Meta:
        model=Categoria
        fields =['nombre','codigo_clasificacion']
        widgets = {
            'codigo_clasificacion': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
        }

        

almacenes/pedidos/forms.py
from django import forms
from .models import Pedido

class Formualrio_pedido(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['descripcion','cantidad_pedida','unidad_manejo']
        widgets = {
            'descripcion': forms.Textarea(attrs={'class': 'form-control','rows':2}),
            'unidad_manejo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'pieza'}),
            'cantidad_pedido': forms.TextInput(attrs={'class': 'form-control'}),
        }

        

almacenes/persona/forms.py
from django import forms
from .models import Persona

class Formulario_persona(forms.ModelForm):
    class Meta:
        model = Persona
        fields  ='__all__'
        widgets={
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'cedula_identidad': forms.TextInput(attrs={'class': 'form-control'}),
        }

almacenes/administracion/views.py
from django.shortcuts import render



def vistar_administracion(request):
    return render(request, 'administracion/administracion.html')

almacenes/materiales/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .forms import Formulario_categoria,Formulario_materiales
from django.http import JsonResponse
from django.http import HttpResponse


from django.template.loader import get_template
from .models import Categoria, Materiales

# Create your views here.

def crear_categoria(request):    
    if(request.method == 'POST'):
        formulario= Formulario_categoria(request.POST)
        if formulario.is_valid():
            formulario.save()
            return JsonResponse({'data':True})
        else:
            formulario= Formulario_categoria(request.POST)
            errors=  dict(formulario.errors.items())
            return JsonResponse({'errores':errors})
    else:
        formulario= Formulario_categoria()  
    categorias = Categoria.objects.all().order_by('-fecha_creacion')
    context={
        'form':formulario,
        'categorias':categorias
    }
    return render(request, 'materiales/categoria/formulario.crear.html', context)

def crear_material(request):
    if(request.method=='POST'):
        formulario= Formulario_materiales(request.POST)
        if(formulario.is_valid()):
            codigo= formulario.cleaned_data['codigo']
            codigo_paquete= formulario.cleaned_data['codigo_paquete']
            categoria= formulario.cleaned_data['categoria']
            material= formulario.save()
            material.codigo_paquete= f"{categoria.codigo_clasificacion}-{codigo_paquete }"
            material.codigo=f"{material.codigo_paquete}-{codigo} "
            material.save()
            material.calcular_total_paquetes()
            material.calcular_precio_total()
        else:
            formulario= Formulario_materiales(request.POST)
    else: 
        formulario= Formulario_materiales()
    context={
        'form':formulario
    }
    return render(request, 'materiales/formulario.material.html', context)


def listado_material(request, id_categoria):#lista todos los material por categoria
    listar_productos_categoria= Materiales.objects.select_related('categoria').filter(categoria_id=id_categoria,es_habilitado=True)
    nombre_categoria = Categoria.objects.get(pk=id_categoria)#trae el nombre de la categoria para el sud titulo
    context={
        'data':listar_productos_categoria,
        'nombre_categoria':nombre_categoria
    }
    return render(request, 'materiales/listar_material.html', context)

def informacion_material(request, id_material):
    info_producto= Materiales.objects.get(pk= id_material)
    context={
        'material':info_producto
    }
    return render(request, 'materiales/informacion_material.html', context)

def editar_material(request, id_material):
    material = get_object_or_404(Materiales, pk=id_material)
    formulario_material = Formulario_materiales(request.POST or None, instance= material)
    if request.method == 'POST':
        if formulario_material.is_valid():
            codigo= formulario_material.cleaned_data['codigo']
            codigo_paquete= formulario_material.cleaned_data['codigo_paquete']
            antiguo_codigo_paquete=codigo_paquete.split('-')
            codigo_antiguo=codigo.split('-')
            categoria= formulario_material.cleaned_data['categoria']
            material= formulario_material.save()
            material.codigo_paquete= f"{categoria.codigo_clasificacion}-{antiguo_codigo_paquete[1]}"
            material.codigo=f"{material.codigo_paquete}-{codigo_antiguo[2]} "
            material.save()
            material.calcular_total_paquetes()
            material.calcular_precio_total()
            return HttpResponse('actulizado')
    
    context={
        'form':formulario_material,
        'material': material

    }
    return render(request, 'materiales/formulario.actulizar.material.html', context)

def softDelete(request, id_material, id_categoria): #elimina el material
    material = get_object_or_404(Materiales, pk= id_material)
    categoria = get_object_or_404(Categoria, pk= id_categoria)
    material.es_habilitado= False
    material.save()
    return  redirect("categorias_por_id", id_categoria=categoria.id)



def inprimir(request, id):
    ruta_tamplate ='materiales/informacion_material.html'
    template = get_template(ruta_tamplate)
    mate = get_object_or_404(Materiales, pk=id)
    context = {'material': mate}
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    pisa_status = pisa.CreatePDF(html, dest=response)
    return response

almacenes/proveedor/views.py
from django.shortcuts import render, redirect, HttpResponse
from django_countries import countries ##sale de aqui todos los paises
from ..persona.models import Persona
from .models import Proveedor
from django.db import transaction
from django.contrib.auth.decorators import login_required

def listar_proveedores(request):
    #id_use=request.user.id   //recuepra el id del usuario
    listar_proveedores = Proveedor.objects.select_related('persona').all()
    return render(request, 'proveedor/index.html',{'proveedores':listar_proveedores})


def formulario_proveedor(request):
    if(request.method == 'POST'):
        empresa = request.POST['empresa']
        nit = request.POST['nit']
        nombre = request.POST['nombre']
        apellidos = request.POST['apellidos']
        cedula_identidad = request.POST['cedula_identidad']
        correo = request.POST['correo']
        telefono = request.POST['telefono']
        direccion = request.POST['direccion']
        pais = request.POST['pais'] 
     
       
        persona= Persona.objects.create(cedula_identidad= cedula_identidad, nombre= nombre, apellidos= apellidos)
        Proveedor.objects.create(empresa=empresa, nit= nit, correo= correo, telefono=telefono,pais=pais ,direccion= direccion, persona=persona)
       
        
        return redirect('listar_proveedor')
    return  render(request, 'proveedor/formulario.html', {'paises':countries})
def actulizar_proveedor(request):
    return  render(request, 'proveedor/actualizar.formulario.html')

almacenes/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    pass

almacenes/templates/usuarios/actulizar_cuenta_formulario.html
{% extends '../base.html' %}

{% block index %}


<div class="container">
    <div class="text-center">
        <h2>Actulizar cuenta</h2>
    </div>
    <form action="{% url 'actulizar_cuenta_usuario' usuario.id persona.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form_persona }}
                <label for="{{ form_usuario.email.id_for_label }}"> {{ form_usuario.email.label}}: </label>
                {{ form_usuario.email }}
                {{form_usuario.email.errors}}
                <label for="{{ form_usuario.item.id_for_label }}"> {{form_usuario.item.label}}:
                </label>
                {{ form_usuario.item}}
                {{form_usuario.item.errors}}
                <label for="{{ form_usuario.cargi.id_for_label }}"> {{form_usuario.cargo.label}}
                </label>
                {{ form_usuario.cargo}}
                {{form_usuario.cargo.errors}}
            </div>
            <div class="col-6">

                <label for="{{ form_usuario.username.id_for_label }}"> {{ form_usuario.username.label}}: </label>
                {{ form_usuario.username }}
                {{form_usuario.username.errors}}
                <label for="{{ form_usuario.password.id_for_label }}"> {{ form_usuario.password.label}}: </label>
                {{ form_usuario.password }}
                <label for="{{ form_usuario.confirmar_password.id_for_label }}">
                    {{form_usuario.confirmar_password.label}}:
                </label>
                {{ form_usuario.confirmar_password }}
                {{form_usuario.confirmar_password.errors}}



                <label for="{{ form_usuario.rol.id_for_label }}"> {{form_usuario.area_trabajo.label}}:
                </label>
                {{ form_usuario.area_trabajo }}
                {{form_usuario.area_trabajo.errors}}


                <label for="{{ form_usuario.rol.id_for_label }}"> {{form_usuario.rol.label}}:
                </label>
                {{ form_usuario.rol }}
                {{form_usuario.rol.errors}}

                <div>
                    <span>Seleccionar permisos solo para Almacen</span> <br>
                    {{ form_usuario.crear.label}}
                    {{ form_usuario.crear}}
                    {{ form_usuario.editar.label}}
                    {{ form_usuario.editar}}
                    {{ form_usuario.eliminar.label}}
                    {{ form_usuario.eliminar}}

                </div>

                <label for="{{ form_usuario.encargado_unidad.id_for_label }}"> {{form_usuario.encargado_unidad.label}}:
                </label>
                {{ form_usuario.encargado_unidad}}
                {{form_usuario.encargado_unidad.errors}}
                <label for="{{ form_usuario.secretaria.id_for_label }}"> {{form_usuario.secretaria.label}}:
                </label>
                {{ form_usuario.secretaria}}
                {{form_usuario.secretaria.errors}}

                <label for="{{ form_usuario.encargado_secretaria.id_for_label }}">
                    {{form_usuario.encargado_secretaria.label}}:
                </label>
                {{ form_usuario.encargado_secretaria}}
                {{form_usuario.encargado_secretaria.errors}}
            </div>
        </div>
        <div class="text-center mt-3">
            <button class="btn btn-success" type="submit">Guardar</button>

        </div>
    </form>


</div>



{% endblock index %}

almacenes/templates/usuarios/mostrar_cuentas.html
{% extends '../base.html' %}
{% load static %}
{% block index %}

<div class="container table-responsive">
    <h2 class="text-center">Cuentas de usuario</h2>
    <div class="row justify-content-start">
        <div class="col-auto me-2">
            <a class="btn btn-success btn-sm" href="{% url 'creando_usuarios' %}">Añadir Usuario</a>
        </div>
        <div class="col-auto me-2 ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal">
                Secretarias
            </button>
        </div>
        <div class="col-auto ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#rolesModal">
                Area
            </button>
        </div>
        <div class="col-auto ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#modalUnidad">
                unidad
            </button>
        </div>
        <div class="col-auto ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#servicios">
                Dir. de servicios
            </button>
        </div>
        <div class="col-auto ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#departamental">
                Dir. departamental
            </button>
        </div>
        <div class="col-auto ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#oficinas">
                Oficinas
            </button>
        </div>

        <div class="col-auto ms-2">
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#rolesModal">
                Crear ruta pedido
            </button>
        </div>

    </div>

    <table class="table table-striped mt-4">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre Completo</th>
                <th scope="col">C.I</th>
                <th scope="col">Usuario</th>
                <th scope="col">Rol</th>
                <th scope="col">Accion</th>
            </tr>
        </thead>
        <tbody>
            {%for cuentas in data %}
            <tr>
                <td>{{cuentas.persona.nombre}} {{cuentas.persona.apellidos}}</td>
                <td>{{cuentas.persona.cedula_identidad}}</td>
                <td>{{cuentas.username}}</td>
                <td>{{cuentas.rol}}</td>


                <td>
                    <a class="btn btn-secondary btn-sm"
                        href="{% url 'actulizar_cuenta_usuario' cuentas.id cuentas.persona.id  %}">Editar</a>
                    <a class="btn btn-danger btn-sm" href="{% url 'eliminar_cuenta' cuentas.id %}">eliminar</a>
                    {%if cuentas.es_activo %}
                    <a class="btn btn-warning btn-sm" href="{% url 'desactivar_cuenta' cuentas.id %}">Desactivar</a>
                    {%else%}
                    <a class="btn btn-success btn-sm" href="{% url 'activar_cuenta' cuentas.id %}">Activar</a>
                    {% endif %}

                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>


    <!--modal secretaria-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Secreatarias</h5>

                </div>
                <div class="modal-body">
                    <div class="col-auto me-2 ms-2">
                        <form id="form_secretaria" action="{%url 'crear_secretaria_listar' %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-6">
                                    <label for="id_secretaria">Nombre secretaria</label>
                                    <input type="text" id="id_secretaria" name="secretaria" class="form-control"
                                        required>
                                    <span id="error"></span>
                                </div>
                                <div class="col-2" style="margin-top: 28px;">
                                    <button id="guardar_secretaria" class="btn btn-success btn-sm"
                                        type="submit">Añadir</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <table class="table ">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Secreataria</th>
                            </tr>
                        </thead>
                        <tbody id="tbody_table">

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>




    <!--fin modal Area de tarabajo-->


    <div class="modal fade" id="modalUnidad" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Unidad</h5>

                </div>
                <div class="modal-body">
                    <div class="col-auto me-2 ms-2">
                        <form id="unidadform" action="{%url 'unidad' %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-6">
                                    <label for="id_secretaria">Nombre unidad</label>
                                    <input type="text" id="id_secretaria" name="unidad" class="form-control" required>
                                    <span id="error_unidad"></span>
                                </div>
                                <div class="col-2" style="margin-top: 28px;">
                                    <button id="unidad" class="btn btn-success btn-sm" type="submit">Añadir</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <table class="table ">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Unidad</th>
                            </tr>
                        </thead>
                        <tbody id="tbody_table_unidad">

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>








    <div class="modal fade" id="oficinas" tabindex="-1" role="dialog" aria-labelledby="oficinas" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Oficinas</h5>

                </div>
                <div class="modal-body">
                    <div class="col-auto me-2 ms-2">
                        <form id="id_form_oficinas" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-6">
                                    <label for="ofcinas">Oficinas</label>
                                    <input type="text" id="oficinas" name="oficinas" class="form-control" required>
                                    <span id="error_oficinas"></span>
                                </div>
                                <div class="col-2" style="margin-top: 28px;">
                                    <button id="id_oficinas" class="btn btn-success btn-sm"
                                        type="submit">Añadir</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% include 'paginador/paginador.html' %}
</div>



{% endblock index %}

{% block js %}



{% endblock js %}